# Generated by Django 5.1.3 on 2024-12-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dateofbirth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='suffix',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
