# Generated by Django 5.1.3 on 2025-01-09 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('address', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentnumber', models.CharField(max_length=100, null=True)),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('middlename', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('suffix', models.CharField(max_length=100, null=True)),
                ('dateofbirth', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('year', models.CharField(max_length=50, null=True)),
                ('course', models.CharField(max_length=50, null=True)),
                ('sectionyear', models.CharField(max_length=50, null=True)),
                ('section', models.CharField(max_length=50, null=True)),
                ('major', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('new_or_old', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10, null=True)),
                ('course_title', models.CharField(max_length=100, null=True)),
                ('year', models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')], null=True)),
                ('semester', models.IntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester')], null=True)),
                ('subject_units_lec', models.IntegerField(null=True)),
                ('subject_units_lab', models.IntegerField(null=True)),
                ('prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_subjects', to='admin_dashboard.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Passed', 'Passed'), ('Failed', 'Failed'), ('Dropped', 'Dropped')], default='Pending', max_length=20)),
                ('instructor', models.CharField(blank=True, max_length=100)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='admin_dashboard.checklist')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.subject')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='subjects',
            field=models.ManyToManyField(through='admin_dashboard.ChecklistItem', to='admin_dashboard.subject'),
        ),
    ]
