# Generated by Django 5.1.3 on 2025-01-08 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('address', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='course_description',
        ),
        migrations.AddField(
            model_name='subject',
            name='course_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_subjects', to='admin_dashboard.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester')], null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')], null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course_code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='subject',
            table=None,
        ),
    ]
