# Generated by Django 5.1.3 on 2025-01-09 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('full', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.program'),
        ),
        migrations.AddField(
            model_name='subject',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='admin_dashboard.program'),
        ),
    ]
