# Generated by Django 5.1.3 on 2024-12-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_student_dateofbirth_student_gender_student_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentnumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
