# Generated by Django 5.1.3 on 2025-01-09 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_program_checklist_program_subject_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='program',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.program'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='program',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='admin_dashboard.program'),
        ),
    ]
