# Generated by Django 5.1.3 on 2025-01-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_alter_checklist_program_alter_subject_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='prerequisite',
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester'), (3, 'Midyear')], null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='prerequisite',
            field=models.ManyToManyField(blank=True, null=True, related_name='dependent_subjects', to='admin_dashboard.subject'),
        ),
    ]
