# Generated by Django 5.1.3 on 2025-01-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_remove_subject_prerequisite_alter_subject_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='prerequisite',
            field=models.ManyToManyField(blank=True, related_name='dependent_subjects', to='admin_dashboard.subject'),
        ),
    ]
