# Generated by Django 5.1.3 on 2024-12-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_student_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='studentnumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
