# Generated by Django 5.1.3 on 2024-12-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_student_delete_personal_info_delete_student_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='new_or_old',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
