# Generated by Django 5.1.3 on 2025-01-17 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_alter_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_fee_name', models.CharField(max_length=50, null=True)),
                ('school_fee_value', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'school_fee',
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_dashboard.program'),
        ),
        migrations.AlterField(
            model_name='student',
            name='suffix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
