# Generated by Django 5.1.3 on 2025-01-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_alter_student_section_alter_student_sectionyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_fee_name', models.CharField(max_length=50, null=True)),
                ('school_fee_value', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'school_fee',
            },
        ),
    ]
