# Generated by Django 5.1.3 on 2025-01-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0010_school_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_fees',
            name='school_fee_value',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
