# Generated by Django 5.1.3 on 2025-01-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0011_alter_school_fees_school_fee_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrollment_dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_period', models.CharField(max_length=50, null=True)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(max_length=12, null=True)),
                ('day', models.IntegerField(max_length=31, null=True)),
            ],
            options={
                'db_table': 'enrollment_date',
            },
        ),
    ]
