# Generated by Django 5.1.3 on 2024-12-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_personal_info_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50, null=True)),
                ('course', models.CharField(max_length=50, null=True)),
                ('sectionyear', models.IntegerField(null=True)),
                ('section', models.IntegerField(null=True)),
                ('major', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('new_or_old', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'student_info',
            },
        ),
    ]
