# Generated by Django 5.1.3 on 2024-12-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_student_new_or_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sectionyear',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
